return {
    data = {
        animations = {
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 4.89,
                        easing = "outsine",
                        end_value = -5,
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "position_x",
                    },
                    {
                        duration = 4.89,
                        easing = "outsine",
                        end_value = -5,
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "position_y",
                    },
                    {
                        duration = 7.47,
                        easing = "outsine",
                        end_value = 0.1,
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 9.15,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 9.15,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 5.11,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "position_y",
                        start_time = 4.89,
                        start_value = -5,
                    },
                    {
                        duration = 9.59,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "position_x",
                        start_time = 4.89,
                        start_value = -5,
                    },
                    {
                        duration = 9.2,
                        easing = "insine",
                        end_value = -0.1,
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "rotation_z",
                        start_time = 7.47,
                        start_value = 0.1,
                    },
                    {
                        duration = 10.85,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_x",
                        start_time = 9.15,
                        start_value = 1.1,
                    },
                    {
                        duration = 10.85,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_y",
                        start_time = 9.15,
                        start_value = 1.1,
                    },
                    {
                        duration = 7.9,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "position_y",
                        start_time = 10,
                        start_value = 5,
                    },
                    {
                        duration = 0.95,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "rotation_z",
                        start_time = 16.95,
                        start_value = -0.1,
                    },
                    {
                        duration = 2.1,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "position_y",
                        start_time = 17.9,
                    },
                    {
                        duration = 2.1,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "camera_group",
                        property_id = "rotation_z",
                        start_time = 17.9,
                    },
                },
                duration = 20,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "system/camera/camera.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}