return {
    data = {
        animations = {
            {
                animation_id = "breath",
                animation_keys = {
                    {
                        duration = 0.77,
                        easing = "outsine",
                        end_value = 42,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_value = 40,
                    },
                    {
                        duration = 1.74,
                        easing = "outsine",
                        end_value = 35,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_time = 0.77,
                        start_value = 42,
                    },
                    {
                        duration = 1.49,
                        easing = "outback",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_time = 2.51,
                        start_value = 35,
                    },
                },
                duration = 4,
            },
            {
                animation_id = "eye_wink",
                animation_keys = {
                    {
                        duration = 0.32,
                        easing = "outsine",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.32,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_y",
                        start_value = 2,
                    },
                    {
                        duration = 0.32,
                        easing = "outsine",
                        end_value = 0.4,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.41,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_x",
                        start_time = 0.32,
                        start_value = -2,
                    },
                    {
                        duration = 0.41,
                        easing = "outsine",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_y",
                        start_time = 0.32,
                    },
                    {
                        duration = 0.47,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_y",
                        start_time = 0.32,
                        start_value = 0.4,
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_x",
                        start_time = 0.73,
                        start_value = 2,
                    },
                    {
                        duration = 0.27,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_y",
                        start_time = 0.73,
                        start_value = 3,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 0.87,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.87,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_y",
                        start_value = 2,
                    },
                    {
                        duration = 0.87,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.87,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 4,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "breath",
                    },
                    {
                        duration = 1,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "eye_wink",
                        start_time = 1.25,
                    },
                    {
                        duration = 2,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "eye_spin",
                        start_time = 3.98,
                    },
                    {
                        duration = 2.03,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "breath",
                        start_time = 5.97,
                    },
                },
                duration = 8,
            },
            {
                animation_id = "slide",
                animation_keys = {
                    {
                        duration = 0.09,
                        easing = "outsine",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_value = 40,
                    },
                    {
                        duration = 0.13,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.13,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.18,
                        easing = "outsine",
                        end_value = -1,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_x",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.42,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "top",
                        property_id = "rotation_z",
                        start_time = 0.18,
                        start_value = -1,
                    },
                    {
                        duration = 0.14,
                        easing = "outsine",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_time = 0.22,
                        start_value = 15,
                    },
                    {
                        duration = 0.13,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_x",
                        start_time = 0.24,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.13,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_y",
                        start_time = 0.24,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = -5,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_x",
                        start_time = 0.31,
                        start_value = 5,
                    },
                    {
                        duration = 0.29,
                        easing = "outsine",
                        end_value = 2,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_y",
                        start_time = 0.31,
                        start_value = 2,
                    },
                    {
                        duration = 0.16,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "position_x",
                        start_time = 0.45,
                        start_value = -5,
                    },
                },
                duration = 0.6,
            },
            {
                animation_id = "eye_spin",
                animation_keys = {
                    {
                        duration = 0.44,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.44,
                        easing = "outsine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.58,
                        easing = "outsine",
                        end_value = 35,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_value = 40,
                    },
                    {
                        duration = 2,
                        easing = "outelastic",
                        end_value = 360,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.56,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_x",
                        start_time = 0.44,
                        start_value = 0.8,
                    },
                    {
                        duration = 1.56,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "eye",
                        property_id = "scale_y",
                        start_time = 0.44,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.43,
                        easing = "outsine",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_time = 0.58,
                        start_value = 35,
                    },
                    {
                        duration = 0.81,
                        easing = "outsine",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "top",
                        property_id = "position_y",
                        start_time = 1.01,
                        start_value = 30,
                    },
                },
                duration = 2,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "entity/player/player.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}