return {
    data = {
        animations = {
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 2.69,
                        easing = "outsine",
                        end_value = 460,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "position_y",
                        start_value = 450,
                    },
                    {
                        duration = 6.92,
                        easing = "outsine",
                        end_value = 3.1,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_x",
                        start_value = 3,
                    },
                    {
                        duration = 6.92,
                        easing = "outsine",
                        end_value = 3.1,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_y",
                        start_value = 3,
                    },
                    {
                        duration = 7.06,
                        easing = "outsine",
                        end_value = -90,
                        key_type = "tween",
                        node_id = "blur",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 2.85,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                        start_time = 0.4,
                    },
                    {
                        duration = 1.2,
                        easing = "outsine",
                        end_value = 455,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "position_y",
                        start_time = 2.69,
                        start_value = 460,
                    },
                    {
                        duration = 4.35,
                        easing = "outsine",
                        end_value = 430,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "position_y",
                        start_time = 3.89,
                        start_value = 455,
                    },
                    {
                        duration = 2.85,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                        start_time = 5.45,
                    },
                    {
                        duration = 2.85,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                        start_time = 5.45,
                    },
                    {
                        duration = 9.08,
                        easing = "outsine",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_x",
                        start_time = 6.92,
                        start_value = 3.1,
                    },
                    {
                        duration = 9.08,
                        easing = "outsine",
                        end_value = 3,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "scale_y",
                        start_time = 6.92,
                        start_value = 3.1,
                    },
                    {
                        duration = 8.94,
                        easing = "outsine",
                        end_value = -360,
                        key_type = "tween",
                        node_id = "blur",
                        property_id = "rotation_z",
                        start_time = 7.06,
                        start_value = -90,
                    },
                    {
                        duration = 7.76,
                        easing = "outsine",
                        end_value = 450,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "position_y",
                        start_time = 8.24,
                        start_value = 430,
                    },
                    {
                        duration = 2.85,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                        start_time = 10.76,
                    },
                    {
                        duration = 2.85,
                        easing = "linear",
                        key_type = "animation",
                        property_id = "pulse",
                        start_time = 10.76,
                    },
                },
                duration = 16,
            },
            {
                animation_id = "pulse",
                animation_keys = {
                    {
                        duration = 0.365,
                        easing = "outback",
                        end_value = 0.83,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "scale_x",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.365,
                        easing = "outback",
                        end_value = 0.83,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "scale_y",
                        start_value = 0.8,
                    },
                    {
                        duration = 0.505,
                        easing = "outback",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "scale_x",
                        start_time = 0.365,
                        start_value = 0.83,
                    },
                    {
                        duration = 0.505,
                        easing = "outback",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "icon_logo",
                        property_id = "scale_y",
                        start_time = 0.365,
                        start_value = 0.83,
                    },
                    {
                        duration = 0.09,
                        easing = "outsine",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "blur_glow",
                        property_id = "color_a",
                        start_time = 0.41,
                        start_value = 1,
                    },
                    {
                        duration = 0.21,
                        easing = "outback",
                        end_value = 1.05,
                        key_type = "tween",
                        node_id = "button_text/root",
                        property_id = "scale_x",
                        start_time = 0.48,
                        start_value = 1,
                    },
                    {
                        duration = 0.21,
                        easing = "outback",
                        end_value = 1.05,
                        key_type = "tween",
                        node_id = "button_text/root",
                        property_id = "scale_y",
                        start_time = 0.48,
                        start_value = 1,
                    },
                    {
                        duration = 0.5,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "blur_glow",
                        property_id = "color_a",
                        start_time = 0.5,
                        start_value = 1.3,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "button_text/root",
                        property_id = "scale_x",
                        start_time = 0.7,
                        start_value = 1.05,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "button_text/root",
                        property_id = "scale_y",
                        start_time = 0.7,
                        start_value = 1.05,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "victory",
                animation_keys = {
                    {
                        duration = 1.05,
                        easing = "outback",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "stars_progress_collected/group",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 1.05,
                        easing = "outback",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "stars_progress_collected/group",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 2.67,
                        easing = "outback",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "stars_progress_collected/group",
                        property_id = "rotation_z",
                        start_time = 0.87,
                    },
                    {
                        duration = 0.87,
                        easing = "outsine",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "stars_progress_collected/icon_star",
                        property_id = "color_a",
                        start_time = 0.54,
                        start_value = 1,
                    },
                    {
                        duration = 2.05,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stars_progress_collected/group",
                        property_id = "scale_x",
                        start_time = 1.92,
                        start_value = 1.3,
                    },
                    {
                        duration = 2.05,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stars_progress_collected/group",
                        property_id = "scale_y",
                        start_time = 1.92,
                        start_value = 1.3,
                    },
                    {
                        duration = 1.63,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "stars_progress_collected/icon_star",
                        property_id = "color_a",
                        start_time = 1.41,
                        start_value = 1.3,
                    },
                },
                duration = 4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "entity/menu_gui/menu_gui.gui",
            layers = {
                {
                    color = "73E84C",
                    name = "gui",
                },
                {
                    color = "90D2F6",
                    name = "text",
                },
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}