return {
    data = {
        animations = {
            {
                animation_id = "appear",
                animation_keys = {
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "background",
                        property_id = "color_a",
                        start_value = 0.4,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "glow",
                        property_id = "color_a",
                        start_value = 0.6,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "settings_button_language/root",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "settings_button_menu/root",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "settings_button_reset/root",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "settings_slider_music/root",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "settings_slider_sound/root",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "window",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "window",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.31,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "window",
                        property_id = "scale_x",
                    },
                    {
                        duration = 0.31,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "window",
                        property_id = "scale_y",
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.4,
                        key_type = "tween",
                        node_id = "background",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.19,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "settings_slider_sound/root",
                        property_id = "color_a",
                        start_time = 0.14,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "settings_slider_music/root",
                        property_id = "color_a",
                        start_time = 0.15,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "settings_button_language/root",
                        property_id = "color_a",
                        start_time = 0.17,
                    },
                    {
                        duration = 0.19,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "settings_button_reset/root",
                        property_id = "color_a",
                        start_time = 0.19,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "settings_button_menu/root",
                        property_id = "color_a",
                        start_time = 0.2,
                    },
                    {
                        duration = 0.17,
                        easing = "outsine",
                        end_value = 0.6,
                        key_type = "tween",
                        node_id = "glow",
                        property_id = "color_a",
                        start_time = 0.23,
                    },
                },
                duration = 0.4,
            },
            {
                animation_id = "disappear",
                animation_keys = {
                    {
                        duration = 0.04,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "glow",
                        property_id = "color_a",
                        start_value = 0.6,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "window",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.2,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "window",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "background",
                        property_id = "color_a",
                        start_value = 0.4,
                    },
                },
                duration = 0.25,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "entity/window_settings/window_settings.gui",
            layers = {
                {
                    color = "73E84C",
                    name = "gui",
                },
                {
                    color = "90D2F6",
                    name = "text",
                },
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}