return {
    data = {
        animations = {
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 0.92,
                        easing = "outsine",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.33,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_x",
                        start_time = 0.42,
                        start_value = 1,
                    },
                    {
                        duration = 0.33,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_y",
                        start_time = 0.42,
                        start_value = 1,
                    },
                    {
                        duration = 0.13,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_a",
                        start_time = 0.74,
                        start_value = 1,
                    },
                    {
                        duration = 0.58,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_a",
                        start_time = 0.87,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.65,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_x",
                        start_time = 0.75,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.65,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_y",
                        start_time = 0.75,
                        start_value = 0.9,
                    },
                    {
                        duration = 1.66,
                        easing = "insine",
                        end_value = 30,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "position_y",
                        start_time = 0.92,
                        start_value = -10,
                    },
                    {
                        duration = 0.33,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_x",
                        start_time = 2.25,
                        start_value = 1,
                    },
                    {
                        duration = 0.33,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_y",
                        start_time = 2.25,
                        start_value = 1,
                    },
                    {
                        duration = 0.65,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_x",
                        start_time = 2.58,
                        start_value = 0.9,
                    },
                    {
                        duration = 0.65,
                        easing = "outelastic",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "scale_y",
                        start_time = 2.58,
                        start_value = 0.9,
                    },
                    {
                        duration = 1.25,
                        easing = "inoutsine",
                        key_type = "tween",
                        node_id = "goal",
                        property_id = "position_y",
                        start_time = 2.58,
                        start_value = 30,
                    },
                },
                duration = 4,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "entity/tile_finish/tile_finish.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}