return {
    data = {
        animations = {
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 1.66,
                        easing = "outsine",
                        end_value = -44.181,
                        key_type = "tween",
                        node_id = "blur_1",
                        property_id = "rotation_z",
                        start_value = -39.181476593018,
                    },
                    {
                        duration = 1.66,
                        easing = "outsine",
                        end_value = 77.008,
                        key_type = "tween",
                        node_id = "blur_2",
                        property_id = "rotation_z",
                        start_value = 82.007698059082,
                    },
                    {
                        duration = 0.71,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "blur_1#sprite",
                        property_id = "color_a",
                        start_time = 0.77,
                        start_value = 1,
                    },
                    {
                        duration = 0.71,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "blur_2#sprite",
                        property_id = "color_a",
                        start_time = 1.21,
                        start_value = 1,
                    },
                    {
                        duration = 0.39,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "blur_1#sprite",
                        property_id = "color_a",
                        start_time = 1.48,
                        start_value = 0.5,
                    },
                    {
                        duration = 1.9,
                        easing = "outsine",
                        end_value = -24.181,
                        key_type = "tween",
                        node_id = "blur_1",
                        property_id = "rotation_z",
                        start_time = 1.66,
                        start_value = -44.181,
                    },
                    {
                        duration = 1.9,
                        easing = "outsine",
                        end_value = 97.008,
                        key_type = "tween",
                        node_id = "blur_2",
                        property_id = "rotation_z",
                        start_time = 1.66,
                        start_value = 77.008,
                    },
                    {
                        duration = 0.34,
                        easing = "outsine",
                        end_value = 0.2,
                        key_type = "tween",
                        node_id = "blur_1#sprite",
                        property_id = "color_a",
                        start_time = 1.87,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.66,
                        easing = "outsine",
                        end_value = 0.2,
                        key_type = "tween",
                        node_id = "blur_2#sprite",
                        property_id = "color_a",
                        start_time = 1.96,
                        start_value = 0.5,
                    },
                    {
                        duration = 1.44,
                        easing = "outsine",
                        end_value = -39.181,
                        key_type = "tween",
                        node_id = "blur_1",
                        property_id = "rotation_z",
                        start_time = 3.56,
                        start_value = -24.181,
                    },
                    {
                        duration = 1.44,
                        easing = "outsine",
                        end_value = 82.008,
                        key_type = "tween",
                        node_id = "blur_2",
                        property_id = "rotation_z",
                        start_time = 3.56,
                        start_value = 97.008,
                    },
                    {
                        duration = 0.396,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "blur_1#sprite",
                        property_id = "color_a",
                        start_time = 3.25,
                        start_value = 0.2,
                    },
                    {
                        duration = 0.396,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "blur_2#sprite",
                        property_id = "color_a",
                        start_time = 3.401,
                        start_value = 0.2,
                    },
                    {
                        duration = 0.91,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "blur_1#sprite",
                        property_id = "color_a",
                        start_time = 3.646,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.91,
                        easing = "outsine",
                        end_value = 0.5,
                        key_type = "tween",
                        node_id = "blur_2#sprite",
                        property_id = "color_a",
                        start_time = 3.8,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.38,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "blur_1#sprite",
                        property_id = "color_a",
                        start_time = 4.62,
                        start_value = 0.5,
                    },
                    {
                        duration = 0.29,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "blur_2#sprite",
                        property_id = "color_a",
                        start_time = 4.71,
                        start_value = 0.5,
                    },
                },
                duration = 5,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "entity/field_torch/field_torch.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}