return {
    data = {
        animations = {
            {
                animation_id = "change",
                animation_keys = {
                    {
                        duration = 0.07,
                        easing = "outsine",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.07,
                        easing = "outsine",
                        end_value = 74,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "position_x",
                        start_value = 69,
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = -5,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "outsine",
                        end_value = 1.1,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "color_a",
                        start_time = 0.07,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.23,
                        easing = "outsine",
                        end_value = 69,
                        key_type = "tween",
                        node_id = "text",
                        property_id = "position_x",
                        start_time = 0.07,
                        start_value = 74,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "rotation_z",
                        start_time = 0.08,
                        start_value = -5,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_x",
                        start_time = 0.08,
                        start_value = 1.1,
                    },
                    {
                        duration = 0.22,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_y",
                        start_time = 0.08,
                        start_value = 1.1,
                    },
                },
                duration = 0.3,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "widget/slide_counter/slide_counter.gui",
            layers = {
                {
                    color = "73E84C",
                    name = "gui",
                },
                {
                    color = "90D2F6",
                    name = "text",
                },
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}