return {
    data = {
        animations = {
            {
                animation_id = "empty",
                animation_keys = {
                    {
                        duration = 0.12,
                        easing = "outsine",
                        end_value = 5,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.61,
                        easing = "insine",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_y",
                        start_value = 0.9,
                    },
                    {
                        duration = 0.61,
                        easing = "insine",
                        end_value = 0.8,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.71,
                        easing = "outsine",
                        end_value = 0.3,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.49,
                        easing = "insine",
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "rotation_z",
                        start_time = 0.12,
                        start_value = 5,
                    },
                },
                duration = 1,
            },
            {
                animation_id = "collected",
                animation_keys = {
                    {
                        duration = 0.27,
                        easing = "outback",
                        end_value = -90,
                        key_type = "tween",
                        node_id = "group",
                        property_id = "rotation_z",
                        start_time = 0.42,
                    },
                    {
                        duration = 0.297,
                        easing = "outsine",
                        end_value = 10,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "rotation_z",
                        start_time = 0.09,
                    },
                    {
                        duration = 0.79,
                        easing = "outback",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "color_a",
                        start_time = 0.11,
                        start_value = 0.3,
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 1.2,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_y",
                        start_time = 0.16,
                        start_value = 0.7,
                    },
                    {
                        duration = 0.2,
                        easing = "outback",
                        end_value = 1.3,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_x",
                        start_time = 0.16,
                        start_value = 0.8,
                    },
                    {
                        duration = 0.273,
                        easing = "outback",
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "rotation_z",
                        start_time = 0.387,
                        start_value = 10,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 0.9,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_y",
                        start_time = 0.49,
                        start_value = 1.2,
                    },
                    {
                        duration = 0.4,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "icon",
                        property_id = "scale_x",
                        start_time = 0.49,
                        start_value = 1.3,
                    },
                },
                duration = 1,
                initial_state = "empty",
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "widget/star_counter/single_star.gui",
            layers = {
                {
                    color = "73E84C",
                    name = "gui",
                },
                {
                    color = "90D2F6",
                    name = "text",
                },
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}