return {
    data = {
        animations = {
            {
                animation_id = "idle",
                animation_keys = {
                    {
                        duration = 1.553,
                        easing = "outsine",
                        end_value = 0.84,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 2.775,
                        easing = "outsine",
                        end_value = 55,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 40,
                    },
                    {
                        duration = 3,
                        easing = "outsine",
                        end_value = 0.7,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 3,
                        easing = "outsine",
                        end_value = 1.4,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 6,
                        easing = "linear",
                        end_value = 180,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1.447,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_time = 1.553,
                        start_value = 0.84,
                    },
                    {
                        duration = 3.225,
                        easing = "outsine",
                        end_value = 40,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 2.775,
                        start_value = 55,
                    },
                    {
                        duration = 1.553,
                        easing = "outsine",
                        end_value = 0.84,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_time = 3,
                        start_value = 1,
                    },
                    {
                        duration = 3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "scale_x",
                        start_time = 3,
                        start_value = 0.7,
                    },
                    {
                        duration = 3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "shadow",
                        property_id = "scale_y",
                        start_time = 3,
                        start_value = 1.4,
                    },
                    {
                        duration = 1.447,
                        easing = "insine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_time = 4.553,
                        start_value = 0.84,
                    },
                },
                duration = 6,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "entity/item_star/item_star.collection",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}